feat(winlog): adding Windows support
observeinc/manifests pull request #47
Opened 2022-05-20 03:09 UTC by stefandorsett

2022-05-20 04:24 UTC, jta commented on bases/winlogs/m/fluentd.conf
> +    endpoint "https://collect.observe-eng.com/v1/http/kubernetes/logs?clusterUid=#{ENV['OBSERVE_CLUSTER']}"
This needs to use OBSERVE_COLLECTOR_HOST, OBSERVE_COLLECTOR_PORT I think.

2022-05-20 04:25 UTC, jta commented on bases/winlogs/m/daemonset.yaml
> +          image: fluent/fluentd:v1.14.6-windows-ltsc2019-1.0
Set the image tag in kustomization.yaml

2022-05-20 04:26 UTC, jta commented on bases/winlogs/m/daemonset.yaml
> +        prometheus.io/path: "/api/v1/metrics/prometheus"
Does fluentd actually expose prom metrics?

2022-05-20 04:26 UTC, jta commented on bases/winlogs/m/kustomization.yaml
> +      - FB_DOCKER_MODE_FLUSH=4
Remove any env vars not references in config.

2022-05-24 21:19 UTC, stefandorsett commented on bases/winlogs/m/daemonset.yaml
> +        prometheus.io/path: "/api/v1/metrics/prometheus"
At this point I'm not sure, going to defer this for now

2022-05-24 21:19 UTC, stefandorsett commented on bases/winlogs/m/kustomization.yaml
> +      - FB_DOCKER_MODE_FLUSH=4
updated

2022-05-24 21:19 UTC, stefandorsett commented on bases/winlogs/m/daemonset.yaml
> +          image: fluent/fluentd:v1.14.6-windows-ltsc2019-1.0
updated

2022-05-24 21:19 UTC, stefandorsett commented on bases/winlogs/m/fluentd.conf
> +    endpoint "https://collect.observe-eng.com/v1/http/kubernetes/logs?clusterUid=#{ENV['OBSERVE_CLUSTER']}"
updated

2022-05-24 22:45 UTC, jta requested changes

2022-05-24 22:45 UTC, jta commented on bases/winlogs/m/daemonset.yaml
> +      nodeSelector:
Move this closer to `affinity`, since they both related to scheduling.

2022-05-24 22:45 UTC, jta commented on bases/winlogs/m/fluentd.conf
> +    flush_interval 5s
env var?

2022-05-24 22:45 UTC, jta commented on bases/winlogs/m/kustomization.yaml
> +      - FB_LOG_LEVEL=warn
these should all have `FLUENTD_` prefix rather than `FB_`.

2022-05-24 23:09 UTC, stefandorsett commented on bases/winlogs/m/fluentd.conf
> +    flush_interval 5s
I'll try moving this around to $aoeu form to see if fluentd likes it

2022-05-24 23:10 UTC, stefandorsett commented on bases/winlogs/m/daemonset.yaml
> +      nodeSelector:
makes sense, will do that

2022-05-25 00:21 UTC, stefandorsett commented on bases/winlogs/m/fluentd.conf
> +    flush_interval 5s
no, the ${aoeu} form is reserved for tags, so to collect environment variables we have to drop out into ruby and collect the environment variables from there. It's super ugly

2022-05-25 00:31 UTC, stefandorsett commented on bases/winlogs/m/kustomization.yaml
> +      - FB_LOG_LEVEL=warn
done

2022-05-25 20:28 UTC, jta approved these changes

2022-05-25 20:29 UTC, merged