Refactor bases/traces/ to use base for deamonset. Add otel-collector deployment
observeinc/manifests pull request #78
Opened 2022-10-27 17:24 UTC by aping1

Two goals to this pr
* Create a base with the config and service accounts required for traces
* deamonset and deployment are two branches based on those bases
* for backwards compat: m,l,xs,xl still point to deamonset with their relative patches

==== TEST PLAN
TODO: tested as single deployment with deploy. Prove it here

2022-10-27 17:58 UTC, stefandorsett requested changes

2022-10-27 17:58 UTC, stefandorsett commented on bases/traces/deamonset/kustomization.yaml
> +  - deamonset.yaml
there has been a general rename from daemonset to deamonset. I think we should stick with the spelling that k8s uses

2022-10-27 17:58 UTC, stefandorsett commented on bases/traces/m/deployment.yaml
> +---
If I'm reading this correctly we're running both daemonset and deployment in m, but only daemonset in the others. Should we be doing both or just one in various sizes, and should we be using the deployment base here rather than copying the yaml?

2022-10-27 19:41 UTC, aping1 commented on bases/traces/deamonset/kustomization.yaml
> +  - deamonset.yaml
thank you! my eyes did not catch this.

2022-10-27 19:55 UTC, aping1 commented on bases/traces/m/deployment.yaml
> +---
it should be one or the other. if your run the kustomize bases/traces/deployment you should get all the config with a deployment. If you do it with daemonset(or any of the links) then you should **not** see a deplyoment

2022-10-27 20:36 UTC, aping1 commented
Talked to @ButterB0wl about the sizing for the collector. For small and med, the deamonset makes sense at their respective values so they will remain unchanged. 
* The L will now point to a deployment with 10 replica nodes. We've seen the deamonset behave correctly with <10 nodes and behave poorly as it scales past 100 nodes so were going to use the Large as a way to handle larger clusters with sane start values
* the XL will be depricated for now until we have a even larger usecase.

2022-10-27 22:52 UTC, stefandorsett commented on bases/traces/m/deployment.yaml
> +---
Ok, I see. So in this case since the m kustomization.yaml is only calling into daemonset should this deployment.yaml be removed?
Additionally, do we need to change any state with xs to make it explicitly call into daemonset instead of m?

2022-10-28 19:57 UTC, aping1 commented on bases/traces/m/deployment.yaml
> +---
Ok i deleted the extra deployment.yaml

2022-10-31 19:43 UTC, aping1 commented
kube-state-events is failing livelness checks during the test apply action. Not related to the change. going to merge this today

2022-10-31 20:05 UTC, stefandorsett reviewed
I think the title needs to be updated to conventional commit standards when you finally merge everything down.
As far as testing plan I'd suggest bringing up testbox and installing the different sizes to make sure they're coming through. If that all comes in I think this looks good

2022-11-01 20:28 UTC, stefandorsett approved these changes

2022-11-01 21:43 UTC, aping1 commented
Test are once again failing from random redinesschecks for kube-events. unreleated to the otel collector that works

2022-11-01 21:43 UTC, merged